-- 1) What is the total revenue generated by the company?
SELECT SUM(payment_value) AS _total_revenue
FROM payments;

-- 2) How many total orders were placed by customers?
SELECT COUNT(order_id) AS total_orders
FROM orders;

-- 3) How many unique customers has the company served?
SELECT COUNT(DISTINCT customer_unique_id) AS total_unique_customers
FROM customers;

-- 4) What is the Average Order Value
SELECT SUM(payment_value) / COUNT(DISTINCT order_id) AS avg_order_value
FROM payments;

-- 5) How many orders were delivered successfully
SELECT COUNT(order_id) AS order_count
FROM orders
WHERE order_status ='delivered';

-- 6) What percentage of orders were delivered successfully
SELECT (COUNT(CASE WHEN order_status = 'delivered' THEN 1 END) /COUNT(order_id)) * 100.0 AS order_percentage
FROM orders;
-- OR
SELECT SUM(order_status = 'delivered') / COUNT(order_id) * 100 AS order_percentage
FROM orders;

-- 7) What are the different order statuses, and how many orders belong to each status
SELECT order_status, COUNT(order_id) AS order_count
FROM orders
GROUP BY order_status;

-- 8) Which are the Top 10 states with the highest number of customers
SELECT customer_state, COUNT(DISTINCT customer_unique_id) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY COUNT(customer_id) DESC
LIMIT 10;

-- 9) Which are the Top 10 cities with the highest number of orders
SELECT c.customer_city, COUNT(o.order_id) AS order_count
FROM customers c
INNER JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY c.customer_city
ORDER BY COUNT(o.order_id) DESC
LIMIT 10;

-- 10) Which payment method is used the most by customers
SELECT payment_type, COUNT(payment_type) AS cust_payment_type
FROM payments
GROUP BY payment_type
ORDER BY COUNT(payment_type) DESC
LIMIT 1;

-- 11) What are the Top 10 highest-selling product categories based on total sales revenue
SELECT p.product_category_name, SUM(o.price) AS total_revenue
FROM products p 
INNER JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC
LIMIT 10;

-- 12) Which are the Top 10 products that generated the highest sales revenue
SELECT p.product_id, SUM(o.price) AS total_revenue
FROM products p
INNER JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.product_id
ORDER BY total_revenue DESC
LIMIT 10;

-- 13) What is the average delivery time (in days) for delivered orders
SELECT AVG(delivery_days) AS avg_delivery_days
FROM orders
WHERE order_status = 'delivered';

-- 14) Which are the Top 10 sellers based on total sales revenue
SELECT seller_id, SUM(price) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;

-- 15) Which payment type generated the highest total revenue
SELECT payment_type, SUM(payment_value) AS total_revenue
FROM payments
GROUP BY payment_type
ORDER BY total_revenue DESC
LIMIT 1;

-- 16) How many orders were placed in each year
SELECT purchase_year, COUNT(*) AS order_count
FROM orders
GROUP BY purchase_year
ORDER BY purchase_year;

-- 17) How many orders were placed in each month
SELECT purchase_month, COUNT(*) AS order_count
FROM orders
GROUP BY purchase_month
ORDER BY FIELD(purchase_month,
	'January','February','March','April',
    'May','June','July','August',
    'September','October','November','December');
    
-- 18) Which day of the week receives the highest number of orders
SELECT purchase_weekday, COUNT(order_id) AS order_count
FROM orders
GROUP BY purchase_weekday
ORDER BY order_count DESC
LIMIT 1;

-- 19) What percentage of orders are delayed
 SELECT COUNT( CASE WHEN is_delayed = 1 THEN 1 END) / 
 COUNT(CASE WHEN order_status = 'delivered' THEN 1 END) * 100.0
 AS delayed_order_percentage
 FROM orders;

-- 20) Which Top 10 sellers have sold the highest number of products
SELECT seller_id, COUNT(product_id) AS product_count
FROM order_items
GROUP BY seller_id
ORDER BY product_count DESC
LIMIT 10;

-- 21) Which Top 10 customers have spent the most money
SELECT c.customer_unique_id, SUM(p.payment_value) AS total_spent
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spent DESC
LIMIT 10;
USE retail360;

-- 22) Which product category has the highest average selling price
SELECT p.product_category_name, AVG(o.price) AS avg_selling_price
FROM products p
INNER JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.product_category_name
ORDER BY avg_selling_price DESC
LIMIT 1;

-- 23) Which states generated the highest total revenue
SELECT c.customer_state, SUM(p.payment_value) AS total_revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC
LIMIT 1;

-- 24) Do customers place more orders on weekends or weekdays
SELECT (CASE WHEN is_weekend = 1 THEN 'Weekend' ELSE 'Weekday' END) AS day_type,
COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;

-- 25) Which are the Top 10 cities that generated the highest total revenue
SELECT c.customer_city, SUM(p.payment_value) AS total_revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_city
ORDER BY total_revenue DESC
LIMIT 1;
